USDA.ARS.NPGS/USDA.ARS.GRIN.GRINGlobal.Web.UI/Models/ErrorViewModel.cs
namespace USDA.ARS.GRIN.GRINGlobal.Web.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

USDA.ARS.NPGS/USDA.ARS.GRIN.GRINGlobal.Web.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using USDA.ARS.GRIN.GRINGlobal.Web.UI.Models;

namespace USDA.ARS.GRIN.GRINGlobal.Web.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

USDA.ARS.NPGS/USDA.ARS.GRIN.GRINGlobal.Web.UI/Controllers/PagesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using USDA.ARS.GRIN.GRINGlobal.Web.UI.Models;

namespace USDA.ARS.GRIN.GRINGlobal.Web.UI.Controllers
{
    public class PagesController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public PagesController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Accession()
        {
            return View("~/Views/Pages/Accession.cshtml");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

USDA.ARS.NPGS/USDA.ARS.GRIN.GRINGlobal.Web.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<ul class="usa-card-group">
    <li class="usa-card tablet-lg:grid-col-3 grid-col-3 maxw-sm">
        <div class="usa-card__container">
            <div class="usa-card__header">
                <h4 class="usa-card__heading">
                    <a href="https://npgsweb.ars-grin.gov/gringlobal/search">
                        Accessions (123,456)
                    </a>
                </h4>
            </div>
            <div class="usa-card__body">
                <p style="font-size:35pt;">
                     
                </p>
            </div>
            <div class="usa-card__footer">
                <a href="@Url.Action("Accession","Pages")" class="usa-button">Acessions</a>
            </div>
        </div>
    </li>
    <li class="usa-card tablet-lg:grid-col-3 grid-col-3 maxw-sm">
        <div class="usa-card__container">
            <div class="usa-card__header">
                <h4 class="usa-card__heading">
                    <a href="https://npgsweb.ars-grin.gov/gringlobal/taxon/taxonomysearchcwr" target="_blank" rel="noreferrer">
                        Crop Wild Relatives (1,234)
                    </a>
                </h4>
            </div>
            <div class="usa-card__body">
                 
                <p style="font-size:35pt;">
                </p>
            </div>
            <div class="usa-card__footer">
                <button class="usa-button">Browse</button>
            </div>
        </div>
    </li>
    <li class="usa-card tablet-lg:grid-col-3 grid-col-3 maxw-sm">
        <div class="usa-card__container">
            <div class="usa-card__header">
                <h4 class="usa-card__heading">
                    <a href="https://npgsweb.ars-grin.gov/gringlobal/taxon/taxonomysearch">
                        Taxa (12,345)
                    </a>
                </h4>
            </div>
            <div class="usa-card__body">
                <p style="font-size:35pt;">
                </p>
            </div>
            <div class="usa-card__footer">
                <button class="usa-button">Browse</button>
            </div>
        </div>
    </li>
    <li class="usa-card tablet-lg:grid-col-3 grid-col-3 maxw-sm">
        <div class="usa-card__container">
            <div class="usa-card__header">
                <h4 class="usa-card__heading">
                    <a href="#">
                        Repositories (34)
                    </a>
                </h4>
            </div>
            <div class="usa-card__body">
                <p>
                </p>                 
            </div>
            <div class="usa-card__footer">
                <button class="usa-button">Browse</button>
            </div>
        </div>
    </li>
</ul>

USDA.ARS.NPGS/USDA.ARS.GRIN.GRINGlobal.Web.UI/Views/Shared/Partials/_USWDSBanner.cshtml
 <!-- ******************************************** BEGIN SITE BANNER ***********************************************************-->
<section class="usa-banner site-banner" aria-label="Official website of the United States government,,,,,,">
    <div class="usa-accordion">
        <header class="usa-banner__header">
            <div class="usa-banner__inner">
                <div class="grid-col-auto">
                    <img aria-hidden="true"
                         class="usa-banner__header-flag"
                         src="https://designsystem.digital.gov/assets/img/us_flag_small.png"
                         alt="" />
                </div>
                <div class="grid-col-fill tablet:grid-col-auto" aria-hidden="true">
                    <p class="usa-banner__header-text">
                        An official website of the United States government
                    </p>
                    <p class="usa-banner__header-action">Here’s how you know</p>
                </div>
                <button type="button"
                        class="usa-accordion__button usa-banner__button"
                        aria-expanded="false"
                        aria-controls="gov-banner">
                    <span class="usa-banner__button-text">Here’s how you know</span>
                </button>
            </div>
        </header>
        <div class="usa-banner__content usa-accordion__content" id="gov-banner">
            <div class="grid-row grid-gap-lg">
                <div class="usa-banner__guidance tablet:grid-col-6">
                    <img class="usa-banner__icon usa-media-block__img"
                         src="https://designsystem.digital.gov/assets/img/icon-dot-gov.svg"
                         role="img"
                         alt=""
                         aria-hidden="true" />
                    <div class="usa-media-block__body">
                        <p>
                            <strong>Official websites use .gov</strong><br />A
                            <strong>.gov</strong> website belongs to an official government
                            organization in the United States.
                        </p>
                    </div>
                </div>
                <div class="usa-banner__guidance tablet:grid-col-6">
                    <img class="usa-banner__icon usa-media-block__img"
                         src="https://designsystem.digital.gov/assets/img/icon-https.svg"
                         role="img"
                         alt=""
                         aria-hidden="true" />
                    <div class="usa-media-block__body">
                        <p>
                            <strong>Secure .gov websites use HTTPS</strong><br />A
                            <strong>lock</strong> (
                            <span class="icon-lock">
                                <svg xmlns="http://www.w3.org/2000/svg"
                                     width="52"
                                     height="64"
                                     viewBox="0 0 52 64"
                                     class="usa-banner__lock-image"
                                     role="img"
                                     aria-labelledby="banner-lock-description"
                                     focusable="false">
                                    <title id="banner-lock-title">Lock</title>
                                    <desc id="banner-lock-description">Locked padlock icon</desc>
                                    <path fill="#000000"
                                          fill-rule="evenodd"
                                          d="M26 0c10.493 0 19 8.507 19 19v9h3a4 4 0 0 1 4 4v28a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V32a4 4 0 0 1 4-4h3v-9C7 8.507 15.507 0 26 0zm0 8c-5.979 0-10.843 4.77-10.996 10.712L15 19v9h22v-9c0-6.075-4.925-11-11-11z" />
                                </svg>
                            </span>) or <strong>https://</strong> means you’ve safely connected to
                            the .gov website. Share sensitive information only on official,
                            secure websites.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ********************************************* END SITE BANNER ************************************************************--> 

USDA.ARS.NPGS/USDA.ARS.GRIN.GRINGlobal.Web.UI/Views/Shared/Partials/_USWDSHeader.cshtml
 <!-- ******************************************** BEGIN HEADER ***********************************************************-->
<header class="usa-header usa-header--extended site-header site-header--dark" role="banner">
    <div class="usa-navbar site-header__navbar">
        <div class="usa-logo site-logo" id="logo" style="margin-left:0px;">
            <em class="usa-logo__text site-logo__text">
                <a href="/" title="GRIN-Global Home">
                    <span aria-hidden="true" class="site-title--short">GG</span>
                    <span class="site-title--long">GRIN-Global</span>
                </a>
            </em>
        </div>
        <button type="button" class="usa-menu-btn">Menu</button>
    </div>
</header>
<!-- ********************************************* END HEADER ************************************************************-->

USDA.ARS.NPGS/USDA.ARS.GRIN.GRINGlobal.Web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - USDA.ARS.GRIN.GRINGlobal.Web.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/USDA.ARS.GRIN.GRINGlobal.Web.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">USDA.ARS.GRIN.GRINGlobal.Web.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - USDA.ARS.GRIN.GRINGlobal.Web.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>